package quotes

// NewBabylon5 returns a Source of well-known lines from J. Michael
// Straczynski's *Babylon 5*. Curated collection of iconic moments from the
// series, spanning major characters and story arcs. Used under fair use.
func NewBabylon5() *Source { return newSource("Babylon 5", babylon5) }

// Sourced from Aaron's B5 quote compilation at
// https://scv.bu.edu/~aarondf/b5quotes.html (fan-compiled, treated as
// canonical). Replaced 2026-05-22 after finding LLM-fabricated quotes in the
// previous list.
var babylon5 = []string{
	"Sooner or later, everyone comes to Babylon 5. — Jeffrey Sinclair",
	"Would you prefer to be conscious or unconscious during the mating? I would prefer conscious, but I don't know what your... pleasure threshold is. — G'Kar",
	"The wheel turns, does it not, Ambassador? — G'Kar",
	"Commander, please. On the issue of galactic peace, I am long past innocence and fast approaching apathy. It's all a game -- a paper fantasy of names and borders. Only one thing matters, Commander. Blood calls out for blood. — Londo",
	"They are alone. They are a dying people. We should let them pass. — Kosh Naranek",
	"What do you want, you moon-faced assassin of joy? — Londo",
	"Ambassador, it is not my place to speculate on how anything gets in your bed. — Na'Toth",
	"Let me pass on to you the one thing I've learned about this place: No one here is exactly what he appears. Not Mollari, not Delenn, not Sinclair... and not me. — G'Kar",
	"Mr. Garibaldi, there're days I'm very glad I don't have to think the way you do. — Ivanova",
	"You will fall upon one another like wolves. It will make what we did pale by comparison. The billions who live forever will be a monument to my work, and the billions who are murdered to buy that immortality will be the continuance of my work. Not like us? You will become us. That's my monument. — Ja'Dur",
	"The avalanche has started, it is too late for the pebbles to vote. — Kosh",
	"The universe is driven by the complex interaction between three ingredients: matter, energy, and enlightened self-interest. — G'Kar",
	"Leave this place. They are not for you. Go, leave. Now. — Kosh",
	"It doesn't matter that his Grail may or may not exist, what matters is that he strives for the perfection of his soul and the salvation of his race and that he has never wavered a lost faith. — Delenn",
	"Mr. Gray, I'm grateful the Psi Corps give you purpose in life, but when that purpose includes scanning *my* mind to prove *my* loyalty, it's not only an invasion of my privacy, but my honor. As for fear, if you enter my mind for any reason I will twist your head off and use it for a chamber pot. If you'll excuse me. — Ivanova",
	"There is nothing more annoying than Mr. Garibaldi when he's right. — Ivanova",
	"Ivanova is always right. I will listen to Ivanova. I will not ignore Ivanova's recommendations. Ivanova is God. And if this ever happens again, Ivanova will personally rip your lungs out. Babylon Control out. Civilians. Just kidding about the God part -- no offense. — Susan Ivanova",
	"Now, I go to spread happiness to the rest of the station. It is a terrible responsibility but I have learned to live with it. — Londo",
	"I know, I know. It's a Russian thing. When we're about to do something stupid, we like to catalog the full extent of our stupidity for future reference. — Ivanova",
	"Now, landing thrusters... landing thrusters, hmm. Now if I were a landing thruster, which one of these would I be? — Londo",
	"You take, Zathras die. You leave, Zathras die. Either way, it is bad for Zathras. — Zathras",
	"There comes a time when you look into the mirror and realize that what you see is all that you will ever be. Then you accept it, or you kill yourself. Or you stop looking into mirrors. — Londo",
	"And so it begins. You have forgotten something. — Kosh",
	"Nothing's the same anymore. — Sinclair",
	"I can only conclude that I'm paying off karma at a vastly accelerated rate. — Ivanova",
	"Rules of combat older than contact with other races. Did not mention aliens. Rules change caught up in committee. Not come through yet. — Former Green Drazi Leader",
	"We are dreamers, shapers, singers, and makers. We study the mysteries of laser and circuit, crystal and scanner, holographic demons and invocations of equations. These are the tools we employ and we know many things. — Elric",
	"An old friend of mine once quoted me an ancient Egyptian blessing: God be between you and harm in all the empty places where you must walk. — Sheridan",
	"We are all slaves to our histories. If there is to be a... bright future, we must learn to break those chains. — Delenn",
	"Summoned, I take the place that has been prepared for me. I am Grey. I stand between the candle and the star. We are Grey. We stand between the darkness and the light. — Delenn",
	"Why does any advanced civilization seek to destroy less advanced one? Because the land is strategically valuable, because there are resources that can be cultivated and exploited, but most of all, simply because they can. — G'Kar",
	"The blood is already on my hands. Right or wrong,... I must follow the path... to its end. — Londo",
	"Don't look away, Captain. All life is transitory, a dream. We all come together in the same place, at the end of time. If I don't see you again here, I will see you, in a little while, in a place where no shadows fall. — Delenn",
	"I have been nothing but compassionate and understanding. I mean, all you had to do was to admit you were wrong and I was right and everything would've been fine. — Ivanova",
	"No dictator, no invader, can hold an imprisoned population by the force of arms forever. There is no greater power in the universe than the need for freedom. Against that power governments, and tyrants, and armies can not stand. The Centauri learned this lesson once. We will teach it to them again. Though it take a thousand years, we will be free. — G'Kar",
	"Mr. Garibaldi. I have been on this station long enough to know that you don't ask leading questions unless you already know the answers. So, why don't we just pretend I've lied about it, you've caught me in your web of insufferable logic and cut to the point. — G'Kar",
	"The Babylon project was our last, best hope for peace.... It failed.... But in the year of the Shadow war it became something greater: our last, best hope... for victory. The year is 2260, the place: Babylon 5. — Ivanova",
	"God goes by many names, perhaps some alien sounding, different faces, and history, but all describing the same Creator. We've come here to learn all those names, in hopes of better understanding the One who's behind them. — Theo",
	"We are the universe, trying to understand itself. — Delenn",
	"Good luck, Captain. I think you are about to go where everyone has gone before. — Ivanova",
	"With our basic freedom in stake, no response can be too extreme. There maybe some minor and *temporary* abridgments in the traditionally protected areas, such as speech and association, but only until this crisis is over. — Julie Musante",
	"I'm already attending to my past, my present and what remains of my future. I do not require your assistance. Or your approval. Enjoy your ceremony, Delenn. I intend to have other plans. — Londo",
	"You know, I used to think it was awful that life was so unfair. Then I thought, wouldn't it be much worse if life were fair, and all the terrible things that happen to us come because we actually deserve them? So, now I take great comfort in the general hostility and unfairness of the universe. — Marcus Cole",
	"You can never go wrong with garters.... Hmm, you might. — Vendor",
	"Yes, yes, Zathras is used to being beast of burden to other people's needs. Very sad life. Probably have very sad death, but at least there is symmetry. Go, go, Zathras take care. — Zathras",
	"No-one ever listens to Zathras. Quite mad, they say. It is good that Zathras does not mind. He's even grown to like it. Oh yes. — Zathras",
	"Thin air? Why is it always thin air? Never fat air, chubby air, mostly-fit-could-stand-lose-a-few-pounds air? — Garibaldi",
	"I am a Ranger. We walk in the dark places no others will enter. We stand on the bridge and no-one may pass. We live for the One, we die for the One. — Marcus",
	"May gods stand between you and harm in all the empty places where you must walk. — Ivanova",
	"Our thoughts form the universe, they always matter. — G'Kar",
	"What are a few million lives compared to the glory of becoming a living god? — Cartagia",
	"Words have meaning and names have power. — Lorien",
	"He was gravely wounded at Z'ha'dum. He was dying. He was dead. I did all I could to help him, but I can not create life, only the universe can do that. I can extend, enhance, there is no magic, nothing spiritual about it, only the application of energies, healing and rebuilding cells. — Lorien",
	"You misunderstand me, Prime Minister. I was merely being specific. In my experience, if you can not say what you mean, you can never mean what you say. The details are everything. — Drano",
	"Maybe the doc's right. Embrace the moment. In the end, that's all we have. Trouble will come in its own time, it always does. But that's tomorrow. Give me today, and I will be happy. — Sheridan",
	"I have seen what power does, and I have seen what power costs. The one is never equal to the other. — G'Kar",
	"I'm delirious with joy. It proves that if you confront the universe with good intentions in your heart, it will reflect that and reward your intent. Usually. It just doesn't always do it in the way you expect. — G'Kar",
	"To celebrate this latest victory against the tyranny of a fanatical few who have endangered the lives of our citizens, Clarke proclaimed today a planetary holiday. Curfew has been extended two full hours until 9 PM Earth standard time, so go out and enjoy. — ISN broadcast by Alison Higgins",
	"Touch passion when it comes your way, Stephen. It's rare enough as it is. Don't walk away when it calls you by name. — Marcus",
	"Captain's personal log, September 2nd, 2261. Enough is enough. — Sheridan",
	"Because while I do not know who the enemy is any longer, I do know who my friends are, and that I have not done as well by them as I should. I hope to change that. I hope to do better. — Londo",
	"Mars. I can't believe I'm back on Mars. Three times before this place almost killed me. I swore I'd never give it another chance to finish the job. Humans have got no business being here. No business at all. — Garibaldi",
	"By nature Mr. Garibaldi is rebellious, stubborn, and suspicious. He has an innate distrust to the authority figures. And he is very good at figuring out when conspiracies are taking place and tracking it back to its source. We need that part of him, so I don't wanna risk tampering with him. — Bester",
	"There is nothing to be gained by trying to harm me, I am not the enemy. To be the enemy, I must have some personal stake in what happens to you. I am not interested in that at all. I'm here to do a job, nothing more. You are a name, a file, and a case number, that's all. — Sheridan",
	"It does prove though how everything is a matter of perspective. You see what you think is daylight, and you assume it's morning. Take it away, you think it's night. Offer you a sandwich, if it's convenient, you'll think it's mid-day. The truth is fluid, the truth is subjective. — Sheridan",
	"Engineering, this is General Lefcourt. In case you didn't notice, the enemy just pulled our shorts up over our head and tied them into a knot. You will get the ship under control ASAP, or I will come down there and skin the hide off every last one of you. — Lefcourt",
	"The bitch of it is that you probably did the right thing. But you did it in the wrong way. In the inconvenient way. Now you have to pay the penalty for that. I know it stinks, but that's the way it is. — Susanna Luchenko",
	"Faith sustains us in the hour when reason tells us that we can not continue, that the whole of our whole lives is without meaning. — Alwyn Macomber",
	"Dedicated to all the people who predicted that the Babylon Project would fail in its mission. Faith manages. — Dedication",
	"It is said that the future is always born in pain. The history of war is the history of pain. If we are wise, what is born of that pain matures into the promise of a better world, because we learn that we can no longer afford the mistakes of the past. — G'Kar",
	"On my world, we have learned that an inauguration is simply a signal to assassins that a new target has been set up on the firing range. — Londo",
	"I don't believe this. What is it with this place? I mean, last week someone tries to assassinate Sheridan, and now someone tries to poison Londo. My God! What is wrong with you people? Don't you have anything else better to do? Why don't you get a hobby? Read a book or something? — Vir",
	"You're supposed to be the head of covert intelligence. Right now, I'm not seeing a hell of a lot of intelligence. Covert, overt, or otherwise! — Lochley",
	"Then, as you said to me once: I will see you in a little while, in a place where no shadows fall. — Sheridan",
	"You are a source of constant annoyance to me, Turval, but only because you're right more often than you're wrong. And why should I keep this joy to myself? I choose to share you with the universe. Valen help them all. — Sech Durhan",
	"Our training methods were created by Minbari to serve Minbari. But if there is any lesson to be learned from the humans, it is that we are made stronger by our differences, not weaker. If the Pak'ma'ra cannot learn to be what we think they should be, then perhaps we should learn to use them for what they are. — Delenn",
	"The willow is deceptively strong. It bends, but it does not break. Its roots are deep and can withstand the worst storm. It promises rest, and shade, and cool breezes to those who would find rest beneath it. You have become my willow. and we have all found shelter in your kindness. — Byron",
	"So... When you were emperor, it meant something. Subduer of the Xon and the Shoggren.... Now... Ptttp! Anyone can be emperor. I can be emperor. Vir can be emperor. If Vir can be emperor, a small earth cat can be emperor.... Come on. Talk to me. It's the day of the dead. — Londo",
	"It's bad luck to die on empty stomach. — G'Kar",
	"We should expect some losses on their side, but let's try to keep it within acceptable limits. The Corps is mother, the Corps is father -- in that way these are our children that've gone astray. We have to at least try to bring them in alive so that we can correct their thinking. — Bester",
	"I have been many things in my life, Mollari. I have been silly. I have been quiet when I should have spoken. I have been foolish. And I have wasted far too much time. But I am still Centauri... and I am not afraid. — Regent",
	"Mollari... understand... that I can never forgive your people for what they did to my world. My people can never forgive your people. But I... can forgive... you. — G'Kar",
}
