package quotes

// NewDiscworld returns a Source of well-known lines from Terry
// Pratchett's *Discworld* series. Per-quote attribution varies wildly
// (Death, Vimes, Granny Weatherwax, Vetinari, Rincewind, the Narrator,
// etc.) so each entry carries its own trailing " — Character (Book)"
// suffix. Short curated set used under fair use.
func NewDiscworld() *Source { return newSource("Discworld", discworld) }

var discworld = []string{
	"\"It is said that your life flashes before your eyes just before you die. That is true, it's called Life.\" — Death (The Last Continent)",
	"\"THERE ARE BETTER THINGS IN THE WORLD THAN ALCOHOL, ALBERT.\" \"Oh, yes, sir. But alcohol sort of compensates for not getting them.\" — Death and Albert (Hogfather)",
	"\"HUMANS NEED FANTASY TO BE HUMAN. TO BE THE PLACE WHERE THE FALLING ANGEL MEETS THE RISING APE.\" — Death (Hogfather)",
	"\"TAKE THE UNIVERSE AND GRIND IT DOWN TO THE FINEST POWDER AND SIEVE IT THROUGH THE FINEST SIEVE AND THEN SHOW ME ONE ATOM OF JUSTICE, ONE MOLECULE OF MERCY.\" — Death (Hogfather)",
	"\"YOU NEED TO BELIEVE IN THINGS THAT AREN'T TRUE. HOW ELSE CAN THEY BECOME?\" — Death (Hogfather)",
	"\"CATS. CATS ARE NICE.\" — Death (Sourcery)",
	"\"DON'T THINK OF IT AS DYING, JUST THINK OF IT AS LEAVING EARLY TO AVOID THE RUSH.\" — Death (Good Omens)",
	"\"THERE IS NO JUSTICE. THERE IS JUST ME.\" — Death (Mort)",
	"\"WHAT CAN THE HARVEST HOPE FOR, IF NOT FOR THE CARE OF THE REAPER MAN?\" — Death (Reaper Man)",
	"\"I COULD MURDER A CURRY.\" — Death (Mort)",
	"\"THE ONLY REASON FOR WALKING INTO THE JAWS OF DEATH IS SO'S YOU CAN STEAL HIS GOLD TEETH.\" — Cohen the Barbarian (The Last Hero)",
	"\"SQUEAK.\" — Death of Rats (various)",
	"\"It would seem that you have no useful skill or talent whatsoever. Have you thought of going into teaching?\" — Lord Vetinari (Mort)",
	"\"Don't put your trust in revolutions. They always come round again. That's why they're called revolutions.\" — Lord Vetinari (Night Watch)",
	"\"I believe in freedom. Not many people do, although they will of course protest otherwise.\" — Lord Vetinari (Going Postal)",
	"\"He didn't like culture-vultures, although if pressed he probably would have said he doted on Uncle Vanya.\" — Narrator (Soul Music)",
	"\"I'm afraid we have to insist on democracy, in this city. One man, one vote. I am the Man. I have the Vote.\" — Lord Vetinari (Mort)",
	"\"It is always useful to face an enemy who is prepared to die for his country. This means that both you and he have exactly the same aim in mind.\" — Lord Vetinari (The Last Hero)",
	"\"Genius is always allowed some leeway, once the hammer has been pried from its hands and the blood has been cleaned up.\" — Narrator (Men at Arms)",
	"\"The pen is mightier than the sword if the sword is very short, and the pen is very sharp.\" — Lord Vetinari (The Truth)",
	"\"He was the sort of person who stood on mountaintops during thunderstorms in wet copper armour shouting 'All the gods are bastards.'\" — Narrator (The Colour of Magic)",
	"\"Light thinks it travels faster than anything but it is wrong. No matter how fast light travels, it finds the darkness has always got there first, and is waiting for it.\" — Narrator (Reaper Man)",
	"\"Stories of imagination tend to upset those without one.\" — Terry Pratchett (Narrator, various)",
	"\"Real stupidity beats artificial intelligence every time.\" — Narrator (Hogfather)",
	"\"In the beginning there was nothing, which exploded.\" — Narrator (Lords and Ladies)",
	"\"Coming back from the dead ought to be worth a hangover.\" — Narrator (Reaper Man)",
	"\"The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.\" — Narrator (Diggers)",
	"\"Five exclamation marks, the sure sign of an insane mind.\" — Narrator (Reaper Man)",
	"\"Multiple exclamation marks are a sure sign of a diseased mind.\" — Narrator (Eric)",
	"\"Build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll be warm for the rest of his life.\" — Narrator (Jingo)",
	"\"If you trust in yourself, and believe in your dreams, and follow your star, you'll still get beaten by people who spent their time working hard and learning things.\" — The Hat (The Wee Free Men)",
	"\"It's not worth doing something unless you were doing something that someone, somewhere, would much rather you weren't doing.\" — Narrator (The Last Continent)",
	"\"The whole of life is just like watching a film. Only it's as though you always get in ten minutes after the big picture has started, and no-one will tell you the plot.\" — Narrator (Moving Pictures)",
	"\"Wisdom comes from experience. Experience is often a result of lack of wisdom.\" — Narrator (various)",
	"\"Some humans would do anything to see if it was possible to do it. If you put a large switch in some cave somewhere, with a sign on it saying 'End-of-the-World Switch. PLEASE DO NOT TOUCH', the paint wouldn't even have time to dry.\" — Narrator (Thief of Time)",
	"\"Goodness is about what you do. Not who you pray to.\" — Narrator (Snuff)",
	"\"They say a little knowledge is a dangerous thing, but it's not one half so bad as a lot of ignorance.\" — Narrator (Equal Rites)",
	"\"Sin, young man, is when you treat people as things. Including yourself. That's what sin is.\" — Granny Weatherwax (Carpe Jugulum)",
	"\"Evil begins when you begin to treat people as things.\" — Granny Weatherwax (I Shall Wear Midnight)",
	"\"I ain't been swearing! That'd be a black sin and so I wouldn't, you bloody old fool.\" — Granny Weatherwax (Lords and Ladies)",
	"\"I can't be having with that.\" — Granny Weatherwax (various)",
	"\"You can't make sense out of senselessness.\" — Granny Weatherwax (Wyrd Sisters)",
	"\"Witches don't curtsy.\" — Granny Weatherwax (Wyrd Sisters)",
	"\"There's no greys, only white that's got grubby.\" — Granny Weatherwax (Carpe Jugulum)",
	"\"I'd be the last one to say there ain't somethin' to be said for a young woman bein' free with her favours, but you might at least ask 'em their names first!\" — Nanny Ogg (Maskerade)",
	"\"I MEANT,\" said Ipslore bitterly, \"what is there in this world that makes living worthwhile?\" Death thought about it. \"CATS,\" he said eventually. \"CATS ARE NICE.\" — Death and Ipslore (Sourcery)",
	"\"He'd been wrong, there was a light at the end of the tunnel, and it was a flamethrower.\" — Narrator (Guards! Guards!)",
	"\"It's vital to remember who you really are.\" — Granny Weatherwax (Witches Abroad)",
	"\"You can't go around building a better world for people. Only people can build a better world for people. Otherwise it's just a cage.\" — Granny Weatherwax (Witches Abroad)",
	"\"That's the trouble, you see. When you become a witch, no one minds.\" — Granny Weatherwax (A Hat Full of Sky)",
	"\"This I choose to do. If there is a price, this I choose to pay. If it is my death, then I choose to die. Where this takes me, there I choose to go. I choose. This I choose to do.\" — Granny Weatherwax (Wintersmith)",
	"\"It's not as if it's not a fine and noble cause, lad. Granny Weatherwax always said you had to do what the heart tells you.\" — Nanny Ogg (Lords and Ladies)",
	"\"Most witches don't believe in gods. They know that the gods exist, of course. They even deal with them occasionally. But they don't believe in them. They know them too well.\" — Narrator (Witches Abroad)",
	"\"You can't trust any bugger further than you can throw him, and there's nothing you can do about it, so let's have a drink.\" — Nanny Ogg (Maskerade)",
	"\"Don't trust the cannibal just 'cos he's usin' a knife and fork!\" — Nanny Ogg (Witches Abroad)",
	"\"Inside every old person is a young person wondering what the hell happened.\" — Cohen the Barbarian (Mort)",
	"\"What an octopus, eh?\" \"Eldritch.\" \"What's eldritch?\" \"Oh... mysterious. And weird.\" — Nanny Ogg and Granny Weatherwax (Witches Abroad)",
	"\"I'd rather be a rising ape than a falling angel.\" — Terry Pratchett (attributed via Discworld)",
	"\"Time is a drug. Too much of it kills you.\" — Narrator (Small Gods)",
	"\"Just because someone's a member of an ethnic minority doesn't mean they're not a nasty small-minded little jerk.\" — Sam Vimes (Snuff)",
	"\"A man is not dead while his name is still spoken.\" — Narrator (Going Postal)",
	"\"The truth may be out there, but the lies are inside your head.\" — Narrator (Hogfather)",
	"\"It's still magic even if you know how it's done.\" — Narrator (A Hat Full of Sky)",
	"\"The presence of those seeking the truth is infinitely to be preferred to the presence of those who think they've found it.\" — Narrator (Monstrous Regiment)",
	"\"He could see Why. Why didn't seem to do much.\" — Narrator (Wyrd Sisters)",
	"\"Always be wary of any helpful item that weighs less than its operating manual.\" — Terry Pratchett (Jingo)",
	"\"If you have enough book space, I don't have to talk to you.\" — Terry Pratchett (attributed)",
	"\"Always remember that the crowd that applauds your coronation is the same crowd that will applaud your beheading. People like a show.\" — Lord Vetinari (Going Postal)",
	"\"I have known and worked with many great men, and the secret of greatness, so far as I have been able to deduce it, is that they don't waste time arguing the toss with little men.\" — Lord Vetinari (Making Money)",
	"\"Some people are heroes. And some people jot down notes.\" — Narrator (Monstrous Regiment)",
	"\"He liked cigars big enough to balance a small kingdom on.\" — Narrator (Guards! Guards!)",
	"\"In and out in five minutes, that was the Vimes way.\" — Narrator (Night Watch)",
	"\"Personal isn't the same as important.\" — Sam Vimes (Men at Arms)",
	"\"Coppers liked to say that people shouldn't take the law into their own hands, and they thought they knew what they meant. They were thinking about the JPs, and the courts, and the law. About the law, in fact. But that wasn't what the saying meant, originally.\" — Narrator (Snuff)",
	"\"The reason that clichés become clichés is that they are the hammers and screwdrivers in the toolbox of communication.\" — Narrator (The Truth)",
	"\"Vimes had once discussed the Ephebian idea of 'democracy' with Carrot, and had been rather interested in the idea that everyone had a vote until he found out that while he, Vimes, would have a vote, there was no way in the rules that anyone could prevent Nobby Nobbs from having one as well. Vimes could see the flaw there straight away.\" — Narrator (Feet of Clay)",
	"\"The thing about Mr Vimes was that he was honest. That was his Boots theory.\" — Narrator (Men at Arms)",
	"\"The reason that the rich were so rich, Vimes reasoned, was because they managed to spend less money.\" — Narrator (Men at Arms)",
	"\"Take it from me, whenever you see a bunch of buggers puttering around talking about truth and beauty and the best way of attacking Ethics, you can bet your sandals it's all because dozens of other poor buggers are doing all the real work around the place.\" — Didactylos (Small Gods)",
	"\"There's a saying that all roads lead to Ankh-Morpork. And it's wrong. All roads lead away from Ankh-Morpork, but sometimes people walk along them the wrong way.\" — Narrator (Mort)",
	"\"Ankh-Morpork had dallied with many forms of government and had ended up with that form of democracy known as One Man, One Vote. The Patrician was the Man; he had the Vote.\" — Narrator (Mort)",
	"\"Carrot had been told by his father, who knew about these things, never to trust a man with no sense of humour. And Vimes... had a fine, well-developed sense of humour. Carrot was pretty sure of that, because he had on occasion seen Vimes laugh.\" — Narrator (Men at Arms)",
	"\"All dwarfs have beards and wear up to twelve layers of clothing. Gender is more or less optional.\" — Narrator (The Fifth Elephant)",
	"\"He liked the idea of democracy. You had to have someone everyone distrusted, he said; that way, everyone was satisfied.\" — Sam Vimes (Snuff)",
	"\"Carrot is honest. He has a kind of honesty that makes it almost impossible for him to lie. He thinks the truth is the most important thing.\" — Narrator (Guards! Guards!)",
	"\"Personal, but not private. That was the motto of the Watch.\" — Narrator (Night Watch)",
	"\"As they say in Discworld, we are trying to unravel the Mighty Infinite using a language which was designed to tell one another where the fresh fruit was.\" — Terry Pratchett (interview, attributed)",
	"\"Rincewind had been told that death was just like going into another room. The difference is, when you shout, 'Where's my clean socks?', you don't get an answer.\" — Narrator (Interesting Times)",
	"\"I'm not afraid of Death. I just don't want to be there when it happens.\" — Rincewind (The Light Fantastic)",
	"\"It is well known that a vital ingredient of success is not knowing that what you're attempting can't be done.\" — Narrator (Equal Rites)",
	"\"Education was a bit like a communicable sexual disease. It made you unsuitable for a lot of jobs and then you had the urge to pass it on.\" — Narrator (Hogfather)",
	"\"Ook.\" — The Librarian (various)",
	"\"The Librarian was, of course, very much in favor of reading in general, but readers in particular got on his nerves.\" — Narrator (Men at Arms)",
	"\"He'd been hoping to surprise the burglar, ideally with a heavy blow to the head, but the burglar had been a step ahead.\" — Narrator (Guards! Guards!)",
	"\"A good bookshop is just a genteel Black Hole that knows how to read.\" — Narrator (Guards! Guards!)",
	"\"It was so much easier to blame it on Them. It was bleakly depressing to think that They were Us. If it was Them, then nothing was anyone's fault. If it was us, what did that make Me? After all, I'm one of Us. I must be. I've certainly never thought of myself as one of Them.\" — Narrator (Jingo)",
	"\"The whole reason for having rulers was so that people didn't have to think all the time.\" — Narrator (Wyrd Sisters)",
	"\"Why do you go away? So that you can come back. So that you can see the place you came from with new eyes and extra colors.\" — Terry Pratchett (A Hat Full of Sky)",
	"\"This isn't life in the fast lane, it's life in the oncoming traffic.\" — Terry Pratchett (attributed)",
	"\"Susan hated Literature. She'd much prefer to read a good book.\" — Narrator (Soul Music)",
	"\"Susan had learned the bonelessly defiant glare of the cat early in life.\" — Narrator (Hogfather)",
	"\"It wasn't blood, in fact. It was just red ink. Most of the people who came in here were thinking about blood, anyway.\" — Susan Sto Helit (Hogfather)",
	"\"The trouble was that he was talking in philosophy but they were listening in gibberish.\" — Narrator (Small Gods)",
	"\"If you don't turn your life into a story, you just become a part of someone else's story.\" — Terry Pratchett (The Amazing Maurice and His Educated Rodents)",
	"\"If you have to look along the shaft of an arrow from the wrong end, if a man has you entirely at his mercy, then hope like hell that man is an evil man. Because the evil like power, power over people, and they want to see you in fear. They want you to know you're going to die. So they'll talk. They'll gloat. They'll watch you squirm. They'll put off the moment of murder like another man will put off a good cigar. So hope like hell your captor is an evil man. A good man will kill you with hardly a word.\" — Vetinari (The Last Hero)",
	"\"Why is it, when I dial 'M for Murder', I always get a wrong number?\" — Moist von Lipwig (Going Postal)",
	"\"The opera house, she realized, was nothing like a palace of art. It was a fortress against the world, full of music and madness and people doing very technical things with bits of canvas.\" — Narrator (Maskerade)",
	"\"Tiffany Aching wondered if all the world was a story. It probably was.\" — Narrator (Wintersmith)",
	"\"Land Under Wave. Land of the Old. Land of the Sleepers. Land of Heroes. Land of the Frozen Sea. Land of Memory. Land Beyond. It calls to me.\" — Tiffany Aching (I Shall Wear Midnight)",
	"\"First Sight is when you can see what's really there, and Second Thoughts are when you think about what you're thinking. And in Tiffany's case, there were sometimes Third Thoughts and Fourth Thoughts.\" — Narrator (A Hat Full of Sky)",
	"\"Crivens!\" — Rob Anybody, Nac Mac Feegle (The Wee Free Men)",
	"\"Nae king! Nae quin! Nae laird! Nae master! We willna' be fooled again!\" — Nac Mac Feegle (The Wee Free Men)",
	"\"Stories don't care who takes part in them. All that matters is that the story gets told, that the story repeats.\" — Granny Weatherwax (Witches Abroad)",
	"\"People's whole lives do pass in front of their eyes before they die. The process is called 'living'.\" — Terry Pratchett (The Last Continent)",
	"\"Nobby, if you stick your hand in your pocket one more time...\" — Sam Vimes (Feet of Clay)",
	"\"Detritus had found that the secret of being a good policeman was to find someone you could trust and tell them everything, which was generally Vimes, except for the bits about his mother.\" — Narrator (Thud!)",
	"\"Lawn-fertilizer-on-a-stick.\" — Detritus, on weaponry (Thud!)",
	"\"That's right, sergeant. We're THE LAW.\" — Detritus (various)",
	"\"What goes around comes around. If not punctually.\" — Narrator (Witches Abroad)",
	"\"The IQ of a mob is the IQ of its most stupid member divided by the number of mobsters.\" — Terry Pratchett (Jingo)",
}
