package quotes

// NewStarTrek returns a Source of well-known lines from across the Star
// Trek universe, spanning 11 series and films. Curated collection of iconic
// moments spanning TOS through Prodigy.
func NewStarTrek() *Source { return newSource("Star Trek", starTrek) }

var starTrek = []string{
	// The Original Series (TOS)
	"\"Live long and prosper.\" — Spock (TOS)",
	"\"Logic is the beginning of wisdom, not the end.\" — Spock (ST VI)",
	"\"The needs of the many outweigh the needs of the few. Or the one.\" — Spock (ST II)",
	"\"I have been, and always shall be, your friend.\" — Spock (ST II)",
	"\"Insufficient facts always invite danger.\" — Spock (TOS)",
	"\"Change is the essential process of all existence.\" — Spock (TOS)",
	"\"Risk is part of the game if you want to sit in that chair.\" — Captain Kirk (TOS)",
	"\"I'm a doctor, not a [blank].\" — Dr. McCoy (TOS)",
	"\"He's dead, Jim.\" — Dr. McCoy (TOS)",
	"\"In an insane society, the sane man must appear insane.\" — Spock (TOS)",
	"\"You know, I have a pet theory about why the Klingons attack with such ferocity. It's because their ship is a mess.\" — Captain Kirk (TOS)",
	"\"I've never known a system that could stand up to a starship captain's intuition.\" — Captain Kirk (TOS)",
	"\"I find I am not quite that omniscient.\" — Spock (TOS)",
	"\"To boldly go where no one has gone before.\" — Captain Kirk (TOS)",
	"\"I am Spock. This is Jim. We are going to find out what's going on here.\" — Spock (TOS)",
	"\"A life is not important except in the impact it has on other lives.\" — Jackie Robinson (often misattributed to Spock via TOS)",

	// The Animated Series (TAS)
	"\"One more step and we'll all be cinders.\" — Captain Kirk (TAS)",
	"\"I wish I could say it was a pleasure.\" — Spock (TAS)",
	"\"Fascinating.\" — Spock (TAS)",
	"\"The Enterprise is my life.\" — Captain Kirk (TAS)",
	"\"We were not meant to die on such a day.\" — Spock (TAS)",
	"\"Your logic is appealing, Spock. I intend to follow it.\" — Captain Kirk (TAS)",

	// The Next Generation (TNG)
	"\"Make it so.\" — Captain Picard (TNG)",
	"\"Engage.\" — Captain Picard (TNG)",
	"\"There are four lights.\" — Captain Picard (TNG)",
	"\"It is possible to commit no mistakes and still lose. That is not a weakness. That is life.\" — Captain Picard (TNG)",
	"\"Things are only impossible until they're not.\" — Captain Picard (TNG)",
	"\"The line must be drawn here. This far, no further.\" — Captain Picard (ST: First Contact)",
	"\"Tea. Earl Grey. Hot.\" — Captain Picard (TNG)",
	"\"With the first link, the chain is forged. The first speech censured, the first thought forbidden, the first freedom denied, chains us all irrevocably.\" — Captain Picard (TNG)",
	"\"The first duty of every Starfleet officer is to the truth.\" — Captain Picard (TNG)",
	"\"I'd like to work on that holodeck, a lot.\" — Captain Picard (TNG)",
	"\"Best of Seven\" is what I'll be called.\" — Data (TNG)",
	"\"I am an android, but I am not alive.\" — Data (TNG)",
	"\"Why do you all keep fighting?\" — Q (TNG)",
	"\"Resistance is futile.\" — The Borg (TNG)",
	"\"You will be assimilated. Your biological and technological distinctiveness will be added to our own.\" — Borg Queen (TNG)",
	"\"Today is a good day to die.\" — Worf (TNG/DS9)",
	"\"I do not approve.\" — Worf (TNG)",
	"\"Klingons do not show mercy to their enemies.\" — Worf (TNG)",
	"\"I love the smell of napalm in the morning.\" — Worf (TNG, misquoting Apocalypse Now)",
	"\"Computer, how's that tea?\" — Captain Picard (TNG)",
	"\"It seems we have a common interest.\" — Captain Picard (ST: First Contact)",
	"\"I'm not interested in debating this with you.\" — Captain Picard (TNG)",
	"\"Your argument is logical but your conclusion is false.\" — Q (TNG)",
	"\"All Good Things...\" — Captain Picard (TNG)",

	// Deep Space Nine (DS9)
	"\"It's a faaaake!\" — Quark (DS9)",
	"\"In the long history of military tradition, the rear guard, the men who hold the line and let the others retreat, are accorded the highest honour.\" — Captain Sisko (DS9)",
	"\"It is easy to be a saint in paradise.\" — Benjamin Sisko (DS9)",
	"\"The Dominion War is not about territory; it's about survival.\" — Captain Sisko (DS9)",
	"\"I should have seen it coming. The Dominion always plays the long game.\" — Captain Sisko (DS9)",
	"\"Promenade doesn't close; it just changes shift.\" — Odo (DS9)",
	"\"I'll have what she's having.\" — Quark (DS9)",
	"\"You want to know the secret? First, you can't beat the profit motive.\" — Quark (DS9)",
	"\"Odo, I need you to do something for me.\" — Captain Sisko (DS9)",
	"\"I'm not a god. I'm just a man.\" — Benjamin Sisko (DS9)",
	"\"The Dominion thinks we're weak.\" — Worf (DS9)",
	"\"Such a waste.\" — Dukat (DS9)",
	"\"I never thought I'd say this, but I'm going to miss you.\" — Odo (DS9)",
	"\"The truth is, I'm Cardassian, but I have Bajoran blood.\" — Dukat (DS9)",

	// Voyager (VOY)
	"\"There's coffee in that nebula.\" — Captain Janeway (VOY)",
	"\"Don't tell me it's impossible — until after I've already done it.\" — Captain Janeway (VOY)",
	"\"We're not just going home. We're bringing home a message: that the Voyager made it across the Delta Quadrant.\" — Captain Janeway (VOY)",
	"\"I am the Doctor.\" — The EMH (VOY)",
	"\"I enjoy data.\" — The EMH (VOY)",
	"\"Captain, there's a ship heading our way at warp 8.\" — Tuvok (VOY)",
	"\"I am Ktarian. I enjoy gaming.\" — The EMH (VOY)",
	"\"You could say I'm a hologram of a very different color.\" — The EMH (VOY)",
	"\"Sanity is relative, Tuvok.\" — Captain Janeway (VOY)",
	"\"Seven of Nine has adapted remarkably well to individuality.\" — The EMH (VOY)",
	"\"I'm beginning to think this Borg woman isn't as bad as I first thought.\" — B'Elanna Torres (VOY)",
	"\"Coffee: the finest organic suspension ever devised.\" — Captain Janeway (VOY)",
	"\"We've been through a lot together, Seven.\" — Captain Janeway (VOY)",
	"\"I will not be assimilated again.\" — Seven of Nine (VOY)",
	"\"Harry, I've lost count of how many times I've almost died.\" — Captain Janeway (VOY)",

	// Enterprise (ENT)
	"\"Faith of the heart will get you everywhere.\" — Captain Archer (ENT)",
	"\"To boldly go... we're not quite ready, but we're going.\" — Captain Archer (ENT)",
	"\"I've had worse days. I think.\" — Captain Archer (ENT)",
	"\"The Vulcans say that humans are too emotional, but I think they're just scared of what we can become.\" — Captain Archer (ENT)",
	"\"Trip, I'm asking you to trust me one more time.\" — Captain Archer (ENT)",
	"\"Science and philosophy are not so different.\" — T'Pol (ENT)",
	"\"I prefer it this way — where I can help directly.\" — Dr. Phlox (ENT)",
	"\"This is what Starfleet was meant to be.\" — Captain Archer (ENT)",
	"\"Humanity's getting better every day.\" — Dr. Phlox (ENT)",
	"\"The future of humanity lies in the stars.\" — Captain Archer (ENT)",

	// Discovery (DSC)
	"\"Trust is a luxury.\" — Captain Lorca (DSC)",
	"\"We need to do better than this.\" — Michael Burnham (DSC)",
	"\"I am First Officer Michael Burnham, and I have something to say.\" — Michael Burnham (DSC)",
	"\"The Federation will come back from this.\" — Captain Lorca (DSC)",
	"\"Burnham, you'll make a fine captain one day.\" — Captain Saru (DSC)",
	"\"I choose to face my demons head-on.\" — Michael Burnham (DSC)",
	"\"We're not so different from you.\" — Michael Burnham (DSC)",
	"\"Book, I need you.\" — Michael Burnham (DSC)",
	"\"Federation or not, this is still Starfleet.\" — Michael Burnham (DSC)",
	"\"The future is not set; we make it ourselves.\" — Michael Burnham (DSC)",
	"\"We're explorers. That's what we do.\" — Captain Burnham (DSC)",

	// Picard (PIC)
	"\"I have to believe that the Federation can be what it once was.\" — Jean-Luc Picard (PIC)",
	"\"I'm still the man who commanded the Enterprise-D.\" — Jean-Luc Picard (PIC)",
	"\"There are still some things worth fighting for.\" — Jean-Luc Picard (PIC)",
	"\"Seven, I need your help.\" — Jean-Luc Picard (PIC)",
	"\"The Borg don't negotiate.\" — Jean-Luc Picard (PIC)",
	"\"I never stopped being a captain.\" — Jean-Luc Picard (PIC)",
	"\"Legacy is what we leave behind.\" — Jean-Luc Picard (PIC)",
	"\"You're going to need backup, sir.\" — Worf (PIC)",
	"\"I'm a Ranger now, Jean-Luc.\" — Seven of Nine (PIC)",

	// Strange New Worlds (SNW)
	"\"I want to explore strange new worlds.\" — Captain Pike (SNW)",
	"\"The number one job of a starship captain is to inspire.\" — Captain Pike (SNW)",
	"\"I know what fate is coming for me, and I choose to change it.\" — Captain Pike (SNW)",
	"\"We're here to seek out the good in people.\" — Captain Pike (SNW)",
	"\"Science needs wonder to thrive.\" — Dr. M'Benga (SNW)",
	"\"I will not accept your resignation.\" — Captain Pike (SNW)",
	"\"The Enterprise will fly again.\" — Captain Pike (SNW)",
	"\"We belong together on that bridge.\" — Spock to Una (SNW)",
	"\"Hope is not a strategy, but it's all we've got.\" — Captain Pike (SNW)",

	// Lower Decks (LD)
	"\"Starfleet is my family.\" — Beckett Mariner (LD)",
	"\"You just gotta believe in yourself.\" — Beckett Mariner (LD)",
	"\"I've seen stranger things than this.\" — Brad Boimler (LD)",
	"\"Starfleet rules, okay?\" — Brad Boimler (LD)",
	"\"We're the lower decks. We do the work nobody else wants to do.\" — Beckett Mariner (LD)",
	"\"Even in Starfleet, love finds a way.\" — Samanthan Rutherford (LD)",
	"\"Command might not appreciate us, but we know what we're doing.\" — Beckett Mariner (LD)",

	// Prodigy (PRO)
	"\"I know we're not supposed to be here, but we have to go.\" — Dal R'El (PRO)",
	"\"I'll protect you. That's what I do.\" — Janeway Holo (PRO)",
	"\"Starfleet is about exploration and making the galaxy a better place.\" — Janeway Holo (PRO)",
	"\"We're all we've got.\" — Gwyn (PRO)",
	"\"I believe in you, even if you don't believe in yourself.\" — Janeway Holo (PRO)",
	"\"The Protostar is our home now.\" — Dal R'El (PRO)",
	"\"Starfleet accepts all kinds.\" — Janeway Holo (PRO)",

	// Films
	"\"Logic is the beginning of wisdom, not the end.\" — Spock (ST VI: The Undiscovered Country)",
	"\"Guess who's coming to dinner.\" — James T. Kirk (ST: Generations)",
	"\"The line must be drawn here.\" — Jean-Luc Picard (ST: First Contact)",
	"\"You pretend to be a god, that makes you nothing but a gerund.\" — Jean-Luc Picard (ST: First Contact)",
	"\"I'd like to make it so.\" — Jean-Luc Picard (ST: Insurrection)",
	"\"It's a big universe.\" — Captain Kirk (ST: The Search for Spock)",
	"\"They want to kill us, but they're not very good at it.\" — Commander Scott (ST: Generations)",
	"\"Your most loyal officer is about to violate your most sacred command.\" — Spock (ST II: The Wrath of Khan)",
	"\"I came back for you.\" — Jean-Luc Picard (ST: First Contact)",
	"\"Nothing unreal exists.\" — Spock (ST IV: The Voyage Home)",
	"\"Double dumb ass on you!\" — Spock (ST IV: The Voyage Home)",
	"\"He thinks he's the second gloomiest thing in the galaxy.\" — Bones (ST IV: The Voyage Home)",
	"\"The road to hell is paved with good intentions.\" — James T. Kirk (ST III: The Search for Spock)",
	"\"We always hope.\" — Spock (ST VI: The Undiscovered Country)",
}
